VMS/Models/Setting.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace VMS.Models
{
    public partial class Setting
    {
        public int Id { get; set; }
        public string SettingKey { get; set; }
        public string SettingValue { get; set; }
    }
}

VMS/ViewModels/PrinterSettingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VMS.ViewModels
{
    public class PrinterSettingViewModel
    {
        [Required]
        public string PrinterName { get; set; }
    }
}

VMS/Controllers/AdminController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VMS.Models;
using System.Linq.Dynamic;
using Microsoft.AspNetCore.Authorization;
using System.Drawing;
using System.Drawing.Printing;
using OpenQA.Selenium;
using OpenQA.Selenium.IE;
using System.IO;
using System.Drawing.Imaging;
using System.Net;
using CoreHtmlToImage;
using VMS.Dtos;
using VMS.Extensions;
using Microsoft.AspNetCore.Mvc.Rendering;
using Firebase.Auth;
using System.Threading;
using Firebase.Storage;

namespace VMS.Controllers
{
   [Authorize]
    public class AdminController : Controller
    {
        int AppointmentId;
        private IWebHostEnvironment environment;
        private VMSDbContext _context;

        public static string apiKey = "AIzaSyD8Kz6UaELdFPGMAxxMzbuhdSvVRKYrDz4";
        public static string Bucket = "showroom-66254.appspot.com";
        public static string AuthEmail = "arkitektzsolutions@gmail.com";
        public static string AuthPassword = "Admin@123#";


        public AdminController(IWebHostEnvironment _environment, VMSDbContext context)
        {
            environment = _environment;
            _context = context; 
        }

        public IActionResult Index()
        {

            var meetingPurpose = _context.MeetingPurposes.ToList();
            List<SelectListItem> meetingPurposes = new List<SelectListItem>();
            foreach (var item in meetingPurpose) {

                meetingPurposes.Add(new SelectListItem() { 
                    Text = item.Name,
                    Value = item.Id.ToString()
                }); 

                

            }

            ViewBag.MeetingPurposes = meetingPurposes;


            return View();
        }
        public IActionResult LoadData(string filterType, DateTime? startDate, DateTime? endDate, int meetingId)
        {
             
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();

                // Skip number of Rows count  
                var start = Request.Form["start"].FirstOrDefault();

                // Paging Length 10,20  
                var length = Request.Form["length"].FirstOrDefault();

                // Sort Column Name  
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

                // Sort Column Direction (asc, desc)  
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

                // Search Value from (Search box)  
                var searchValue = Request.Form["search[value]"].FirstOrDefault();

                //Paging Size (10, 20, 50,100)  
                int pageSize = length != null ? Convert.ToInt32(length) : 0;

                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;

                // getting all Customer data  
                var appointmentData = (from appointment in _context.Appointments orderby appointment.CreatedDate descending
                                       join meeting in _context.MeetingPurposes on appointment.MeetingPurpose equals meeting.Id
                                       select new
                                       {
                                           appointment.Id,
                                           appointment.FullName,
                                           appointment.PhoneNumber,
                                           appointment.CompanyName,
                                           meeting.Name,
                                           appointment.CarRegistration,
                                           appointment.CheckIn,
                                           appointment.CheckOut,
                                           appointment.CreatedDate,
                                           appointment.MeetingPurpose,
                                           meetingType = meeting.Id
                                       });

                 if (filterType != null) {
                    
                    if (filterType == "CheckIn") {
                         appointmentData = appointmentData.OrderByDescending(x => x.CheckIn).Where(x => x.CheckIn != null && x.CheckOut == null);
                    }
                     
                 }

            if (startDate != null && endDate != null)
            {
                appointmentData = appointmentData.OrderByDescending(x => x.CheckIn).Where(x => x.CreatedDate > startDate && x.CreatedDate < endDate);
            }
            else {

                if (startDate != null) { 
                    appointmentData = appointmentData.OrderByDescending(x => x.CheckIn).Where(x => x.CreatedDate < startDate);
                }

                if (endDate != null) { 
                    appointmentData = appointmentData.OrderByDescending(x => x.CheckIn).Where(x => x.CreatedDate < endDate);
                }

            }

            if (meetingId != 0) {
                appointmentData = appointmentData.OrderByDescending(x => x.CheckIn).Where(x => x.meetingType == meetingId);
            }

            //Sorting  
            if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                  //  appointmentData = appointmentData.OrderBy(sortColumn + " " + sortColumnDirection);
                }
                //Search  
                if (!string.IsNullOrEmpty(searchValue))
                {
                    appointmentData = appointmentData.Where(m => m.FullName == searchValue);
                }

                //total number of rows counts   
                recordsTotal = appointmentData.Count();
                //Paging   
                var data = appointmentData.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data  
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });

           

        }

        public IActionResult LoadGraphData()
        {

            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();

            // Skip number of Rows count  
            var start = Request.Form["start"].FirstOrDefault();

            // Paging Length 10,20  
            var length = Request.Form["length"].FirstOrDefault();

            // Sort Column Name  
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

            // Sort Column Direction (asc, desc)  
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

            // Search Value from (Search box)  
            var searchValue = Request.Form["search[value]"].FirstOrDefault();

            //Paging Size (10, 20, 50,100)  
            int pageSize = length != null ? Convert.ToInt32(length) : 0;

            int skip = start != null ? Convert.ToInt32(start) : 0;

            int recordsTotal = 0;



            // getting all Customer data  
            var appointmentData = (from employee in _context.Employees
                                  select new
                                  {
                                      employee.Id,
                                      employee.Name,
                                      employee.CreatedDate
                                  });

            //Sorting  
            if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
            {
                //  appointmentData = appointmentData.OrderBy(sortColumn + " " + sortColumnDirection);
            }
            //Search  
            if (!string.IsNullOrEmpty(searchValue))
            {
                appointmentData = appointmentData.Where(m => m.Name == searchValue);
            }

            //total number of rows counts   
            recordsTotal = appointmentData.Count();
            //Paging   
            var data = appointmentData.Skip(skip).Take(pageSize).ToList();
            //Returning Json Data  
            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });



        }
        public IActionResult GetAppointment(int Id)
        {
            var model = (from appointment in _context.Appointments.Where(x => x.Id == Id)
                         join meeting in _context.MeetingPurposes on appointment.MeetingPurpose equals meeting.Id
                         select new
                         {
                             appointment.Id,
                             appointment.FullName,
                             appointment.PhoneNumber,
                             appointment.CompanyName,
                             meeting.Name,
                             appointment.MeetingDescription,
                             appointment.CarRegistration,
                             appointment.ProfilePhotoUrl,
                             appointment.VisitingEmployee,
                             appointment.IsFlu

                         }).FirstOrDefault();

            return Json(model);
        }

        [AllowAnonymous]
        public IActionResult PrintPage(int Id) {

            var getPrinterName = _context.Settings.Where(x => x.SettingKey == "Printer").FirstOrDefault();

            AppointmentId = Id;
            System.Drawing.Printing.PrintDocument pd = new System.Drawing.Printing.PrintDocument();
            pd.PrintPage += new PrintPageEventHandler(pd_PrintPage);
            //if (getPrinterName != null) { 
            //    pd.PrinterSettings.PrinterName = getPrinterName.SettingValue;
            //}
            pd.Print();

            return Ok();
        }
        public IActionResult Dashboard() 
        {

            return View();
        }
        [AllowAnonymous]

VMS/Controllers/SettingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VMS.Models;
using VMS.ViewModels;

namespace VMS.Controllers
{
    public class SettingController : Controller
    {
         
        private VMSDbContext _context; 
        public SettingController(VMSDbContext context)
        {
            _context = context;
        }

        public IActionResult PrinterSettings()
        {
            var checkPrinterValue = _context.Settings.Where(x => x.SettingKey == "Printer").FirstOrDefault();
            if (checkPrinterValue != null)
            {
                var model = new PrinterSettingViewModel();
                model.PrinterName = checkPrinterValue.SettingValue;
                return View(model);
            }
            else {
                var model = new PrinterSettingViewModel();
                model.PrinterName = "Not Printer Added";
                return View(model);
            }

           
        }

        [HttpPost]
        public IActionResult PrinterSettings(PrinterSettingViewModel model)
        {
            var checkPrinterValue = _context.Settings.Where(x => x.SettingKey == "Printer").FirstOrDefault();
            if (checkPrinterValue != null)
            {
                checkPrinterValue.SettingValue = model.PrinterName;
                _context.SaveChanges();
            }
            else {
                Setting row = new Setting();
                row.SettingKey = "Printer";
                row.SettingValue = model.PrinterName;
                _context.Settings.Add(row);
                _context.SaveChanges();
            }

            return View(model);
        }


        public IActionResult CredentialsManagers()
        {
            var apiKey = _context.Settings.Where(x => x.SettingKey == "ApiKey").FirstOrDefault();
             
            var model = new EmailConfigViewModel()
            {
                ApiKey = apiKey.SettingValue
            };
            

            return View(model);
        }

        [HttpPost]
        public IActionResult CredentialsManagers(EmailConfigViewModel model)
        {
            var emailConfig = _context.Settings.Where(x => x.SettingKey == "ApiKey").FirstOrDefault();
            if (emailConfig != null) {
                emailConfig.SettingValue = model.ApiKey;
                _context.SaveChanges();
            }

            return View(model);
        }



    }
}

VMS/Views/Setting/CredentialsManagers.cshtml
@model VMS.ViewModels.EmailConfigViewModel
@{
    ViewData["Title"] = "CredentialsManagers";
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
}



<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Api Settings</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Email Settings</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Set ApiKey</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div>
            <form action="@Url.Action("CredentialsManagers","Setting")" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-body">

                    <div class="form-group">
                        <label asp-for="ApiKey"></label>
                        <input asp-for="ApiKey" id="visitingEmployee" class="form-control" placeholder="Enter Api Value" value="@Model.ApiKey">
                        <span asp-validation-for="ApiKey" class="text-danger"></span>
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <div class="row">
                        <button type="submit" class="btn btn-primary col-md-12" style="margin: 0 auto;">
                            Change
                        </button>
                    </div>
                </div>
            </form>


        </div>
    </div>
    <!-- /.card -->

</div>


<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- DataTables  & Plugins -->
<script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/plugins/jszip/jszip.min.js"></script>
<script src="~/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
        asp-fallback-src="~/Identity/lib/jquery-validation/dist/jquery.validate.min.js"
        asp-fallback-test="window.jQuery && window.jQuery.validator"
        crossorigin="anonymous"
        integrity="sha384-rZfj/ogBloos6wzLGpPkkOr/gpkBNLZ6b6yLy4o+ok+t/SAKlL5mvXLr0OXNi1Hp">
</script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.9/jquery.validate.unobtrusive.min.js"
        asp-fallback-src="~/Identity/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
        asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive"
        crossorigin="anonymous"
        integrity="sha384-ifv0TYDWxBHzvAk2Z0n8R434FL1Rlv/Av18DXE43N/1rvHyOG4izKst0f2iSLdds">
</script>
<script>
    $("#container-loader").hide();





</script>

VMS/Views/Setting/PrinterSettings.cshtml
@model VMS.ViewModels.PrinterSettingViewModel
@{
    ViewData["Title"] = "PrinterSettings";
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Printer Settings</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Printer Settings</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Set Printer</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div>
            <form action="@Url.Action("PrinterSettings","Setting")" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-body">




                    <div class="form-group">
                        <label asp-for="PrinterName"></label>
                        <input asp-for="PrinterName" id="visitingEmployee" class="form-control" placeholder="Enter Printer Name" value="@Model.PrinterName">
                        <span asp-validation-for="PrinterName" class="text-danger"></span>
                    </div>



                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <div class="row">
                        <button type="submit" class="btn btn-primary col-md-12" style="margin: 0 auto;">
                            Change
                        </button>
                    </div>
                </div>
            </form>


        </div>
    </div>
    <!-- /.card -->

</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="~/js/webcam.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-4-autocomplete/dist/bootstrap-4-autocomplete.min.js" crossorigin="anonymous"></script>

<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
        asp-fallback-src="~/Identity/lib/jquery-validation/dist/jquery.validate.min.js"
        asp-fallback-test="window.jQuery && window.jQuery.validator"
        crossorigin="anonymous"
        integrity="sha384-rZfj/ogBloos6wzLGpPkkOr/gpkBNLZ6b6yLy4o+ok+t/SAKlL5mvXLr0OXNi1Hp">
</script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.9/jquery.validate.unobtrusive.min.js"
        asp-fallback-src="~/Identity/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
        asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive"
        crossorigin="anonymous"
        integrity="sha384-ifv0TYDWxBHzvAk2Z0n8R434FL1Rlv/Av18DXE43N/1rvHyOG4izKst0f2iSLdds">
</script>
<script>

    $("#container-loader").hide();
    var src = {
    }

    var EmployeeNameArray = [
    ];

    LoadEmployeeToArray();

    function LoadEmployeeToArray() {

                $.ajax({
                    url: "@Url.Action("GetListPrinter", "Admin")",
                    type: "GET",
                    success: function (data) {
                        console.log(data);
                        data.map((item, index) => {
                            console.log(item);
                            src[item.printerName] = item.printerName;
                        });
                        return data;

                    }
                });

    }


    $("#visitingEmployee").autocomplete({
        treshold: 0,
        source: src,
        onSelectItem: onSelectItem,
        highlightClass: 'text-danger',

    });


    function onSelectItem() { }

</script>