VMS/Controllers/WhiteListController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VMS.Hubs;
using VMS.Models;

namespace VMS.Controllers
{
    public class WhiteListController : Controller
    {
        private IWebHostEnvironment environment;
        private VMSDbContext _context;
        private readonly IHubContext<QrCode> _hub;
        public WhiteListController(IWebHostEnvironment _environment, VMSDbContext context, IHubContext<QrCode> hub)
        {
            environment = _environment;
            _context = context;
            _hub = hub;
        }

        public async Task<IActionResult> Index()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult LoadIPAddressData()
        {

            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();

            // Skip number of Rows count  
            var start = Request.Form["start"].FirstOrDefault();

            // Paging Length 10,20  
            var length = Request.Form["length"].FirstOrDefault();

            // Sort Column Name  
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

            // Sort Column Direction (asc, desc)  
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

            // Search Value from (Search box)  
            var searchValue = Request.Form["search[value]"].FirstOrDefault();

            //Paging Size (10, 20, 50,100)  
            int pageSize = length != null ? Convert.ToInt32(length) : 0;

            int skip = start != null ? Convert.ToInt32(start) : 0;

            int recordsTotal = 0;

            // getting all Customer data  
            var employmentData = (from row in _context.WhiteListIpaddresses
                                  select new
                                  {
                                      row.Id,
                                      row.Ipaddress, 
                                      row.Description
                                  });

            //Sorting  
            if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
            {
                //  appointmentData = appointmentData.OrderBy(sortColumn + " " + sortColumnDirection);
            }
            //Search  
            if (!string.IsNullOrEmpty(searchValue))
            {
                employmentData = employmentData.Where(m => m.Ipaddress == searchValue);
            }

            //total number of rows counts   
            recordsTotal = employmentData.Count();
            //Paging   
            var data = employmentData.Skip(skip).Take(pageSize).ToList();
            //Returning Json Data  
            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });



        }

        [HttpPost]
        public IActionResult AddIPAddress(string IPAddress, string Description)
        {
            var checkIpAddress = _context.WhiteListIpaddresses.Where(x => x.Ipaddress == IPAddress).FirstOrDefault();
            if (checkIpAddress != null) {
                return Ok();
            }

            var model = new WhiteListIpaddress()
            {
                Ipaddress = IPAddress,
                Description = Description,
                CreatedDate = DateTime.Now.Date
            };

            _context.WhiteListIpaddresses.Add(model);
            _context.SaveChanges();

            return Ok();
        }


        [HttpPost]
        public IActionResult DeleteIPAddress(int Id) 
        {
            var IPAddress = _context.WhiteListIpaddresses.Where(x => x.Id == Id).FirstOrDefault();
            if (IPAddress != null) {
                _context.WhiteListIpaddresses.Remove(IPAddress);
                _context.SaveChanges();
               
                return Ok();
            }

            return Ok();
            
        }

    }
}

VMS/Views/WhiteList/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">WhiteList</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">WhiteList</li>
                </ol>
            </div>
        </div>
    </div>
</div>


<div class="row" id="WhiteListFormList">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-10">
                        <h3 class="card-title">WhiteList list table</h3>
                    </div>
                    <div class="col-md-2">
                        <button class="btn btn-primary" onclick="AddIPAddressForm()">Add IP Address</button>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table id="dt-ip-addresses-list" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>IP Address</th>
                            <th>Description</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                </table>
            </div>
        </div>
    </div>
</div>


<div class="col-md-12" id="AddIPAddress" style="display:none;">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">IP Address</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div>
            <div class="card-body">
                <div class="form-group">
                    <label for="txtIPAddress">IP Address</label>
                    <input type="text" class="form-control" id="txtIPAddress" placeholder="Enter IP Address">
                    <span class="text-danger" id="val_IPAddress" style="display:none;"> IP Address is required</span>
                </div>

                <div class="form-group">
                    <label for="txtDescription">Description</label>
                    <input type="text" class="form-control" id="txtDescription" placeholder="Description">
                </div>

            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <div class="row">
                    <button type="submit" onclick="SaveIPAddress()" class="btn btn-primary col-md-5" style="margin: 0 auto;">
                        Submit
                    </button>
                    <button type="submit" onclick="CancelIPAddress()" class="btn btn-danger col-md-5" style="margin: 0 auto;">
                        Cancel
                    </button>

                </div>
            </div>
        </div>
    </div>
    <!-- /.card -->


</div>





<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- DataTables  & Plugins -->
<script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/plugins/jszip/jszip.min.js"></script>
<script src="~/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script>
    $("#container-loader").hide();
    var tblIPAddresses= $('#dt-ip-addresses-list').DataTable({
                        "processing": true,
                        "serverSide": true,
                        "filter": true,
                        "orderMulti": false,
                        "ajax": {
                            "url": "@Url.Action("LoadIPAddressData", "WhiteList")",
                            "type": "POST",
                            "datatype": "json"

                        },
                        "columns": [
                            { "data": "ipaddress", "name": "ipaddress", "autoWidth": true },
                            { "data": "description", "name": "description", "autoWidth": true },
                            {
                                data: null,
                                render: function (data, type, row) {
                                    return `<button onClick='DeleteIPAddress(${data.id})' class='btn btn-danger'>Delete</button>`;
                                }
                            },
                        ]

                });


    const AddIPAddressForm = () => {
        $("#txtIPAddress").val('');
        $("#AddIPAddress").show();
        $("#WhiteListFormList").hide();
    }


    const SaveIPAddress = () => {

        const IPAddress = $("#txtIPAddress").val();
        const Description = $("#txtDescription").val();

        if (IPAddress !== "") {
            $('#val_IPAddress').hide();
        } else {
            $('#val_IPAddress').show();
            return;
        }

        $.ajax({
            type: "POST",
            url: "@Url.Action("AddIPAddress", "WhiteList")",
            data: { IPAddress: IPAddress, Description: Description  },
            success: function (response) {

                $("#AddIPAddress").hide();
                $("#WhiteListFormList").show();
                tblIPAddresses.clear().draw();

            },
            failure: function (response) {

            },
            error: function (response) {

            }
        })







    }

    const CancelIPAddress = () => {
        $('#val_IPAddress').hide();
        $("#AddIPAddress").hide();
        $("#WhiteListFormList").show();
    }


    const DeleteIPAddress = (Id) => {

         Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {

                 $.ajax({
                        type: "POST",
                        url: "@Url.Action("DeleteIPAddress", "WhiteList")",
                        data: { Id: Id},
                        success: function (response) {

                            $("#AddIPAddress").hide();
                            $("#WhiteListFormList").show();
                            tblIPAddresses.clear().draw();

                        },
                        failure: function (response) {

                        },
                        error: function (response) {

                        }
                    })


            }
        })



    }

</script>